### ISSUE TITLE
there is a problem when running

### ISSUE THREAD

**Issue by dddddkkk** [taki0112/Group_Normalization-Tensorflow#2]
I want to use gn into CNN , and meet a prolem:
ailed to convert object of type <class 'list'> to Tensor. Contents: [Dimension(None), 2, Dimension(14), Dimension(28), Dimension(32)]. Consider casting elements to a supported type.

this is the code:
def groupnorm(x,gamma,bate,G,eps=1e-5):
x=tf.transpose(x,[0,3,1,2])
N,C,H,W =x.get_shape().as_list()
G=min(G,C)
print('x:',x)
x=tf.reshape(x,[N,G,C//G,H,W])
mean,var = tf.nn.moments(x,[2,3,4],keep_dims=True)
x=(x-mean)/tf.sqrt(var+eps)
gamma=tf.get_variable('gamma',[C],initializer=tf.constant_initializer(1.0))
bate=tf.get_variable('bate',[C],initializer=tf.constant_initializer(1.0))
gamma=tf.reshape(gamma,[1,C,1,1])
bate=tf.reshape(gamma,[1,C,1,1])
x=tf.reshape(x, [N, H, W, C])
output=x*gamma+bate
output=tf.transpose(output,[0,2,3,1])
print('a:',a)
return output

**Comment by taki0112** [comment]
give me some information more ...

1. what is the `shape of x` ?
2. last line, you used `print(a)`, what is the 'a' ?

**Comment by dddddkkk** [comment]
thanks your reply.  when input x ,the x is Tensor("add_4:0", shape=(?, 28, 28, 32), dtype=float32), and the  I can get the a .it  can not work in tihs code"x=tf.reshape(x,[N,G,C//G,H,W])",and meet a prolem:
ailed to convert object of type <class 'list'> to Tensor. Contents: [Dimension(None), 2, Dimension(14), Dimension(28), Dimension(32)]. Consider casting elements to a supported type.

**Comment by taki0112** [comment]
I think 
Maybe it's because the `batch size` is set to None.
please set the batch size to an exact value other than None.

or try this
code change 

```python
N,C,H,W =x.get_shape().as_list()

->
N = tf.shape(x)[0]
C = tf.shape(x)[1]
H = tf.shape(x)[2]
W = tf.shape(x)[3]
```

**Comment by dddddkkk** [comment]
it works.I found the problem ,according to your suggestions.thanks again
